@echo off
echo Installing Tailwind CSS and dependencies...
npm install -D tailwindcss postcss autoprefixer alpinejs
echo Creating Tailwind config...
npx tailwindcss init -p
echo Clearing npm cache...
npm cache clean --force
echo Installation complete! Now run 'npm run dev' to compile assets.
